model: meta-llama/Llama-3.2-1B-Instruct
api_url: https://greg1232--cray-cpu-llama-3-2-1b-instruct-fastapi-app.modal.run
vllm_api_url: https://greg1232--cray-cpu-llama-3-2-1b-instruct-vllm-app.modal.run
