services:

    vllm:
        command: /app/cray/scripts/start_one_server.sh
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
            - "8001:8001"
        volumes:
            - type: bind
              source: ./models
              target: /root/.cache/huggingface
            - type: bind
              source: ./infra
              target: /app/cray/infra
            - type: bind
              source: ./scripts
              target: /app/cray/scripts
            - type: bind
              source: ./ml
              target: /app/cray/ml
        networks:
            - cray-network

networks:
  cray-network:
    name: cray_network

