model: meta-llama/Llama-3.2-3B-Instruct
api_url: https://smi-workspace--cray-nvidia-llama-3-2-3b-instruct-fastapi-app.modal.run #https://greg1232--cray-cpu-llama-3-2-1b-instruct-fastapi-app.modal.run
vllm_api_url: https://smi-workspace--cray-nvidia-llama-3-2-3b-instruct-vllm-app.modal.run #https://greg1232--cray-cpu-llama-3-2-1b-instruct-vllm-app.modal.run
training_job_directory: /app/cray/jobs
