# Default values for cray-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sudnya/scalarlm-rocm
  tag: latest
  pullPolicy: Always

env:
  - name: HIP_VISIBLE_DEVICES
    value: "0"
  - name: ROCR_VISIBLE_DEVICES
    value: "0"
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  externalIP: 10.1.81.248

model: meta-llama/Llama-3.1-8B-Instruct
max_model_length: 4096
gpu_memory_utilization: 0.33
