apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalarlm-jobs
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.jobs_pvc.size }}
  storageClassName: {{ .Values.jobs_pvc.storageClass }}
    #wait_until_bound: false
