apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalarlm-3b-jobs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jobs_pvc.size }}
  storageClassName: {{ .Values.jobs_pvc.storageClass }}
  wait_until_bound: false
