[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "supermi"
version = "0.0.1"
authors = [
  { name="Greg Diamos", email="gregory.diamos@gmail.com" },
]
description = "Supermassive intellgent AI"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "lamini-configuration[yaml]",
    "requests",
    "tqdm",
    "numpy<2.0.0",
    "jsonlines",
    "pandas",
    "azure-storage-blob",
    "scikit-learn",
    "aiohttp",
]

[tool.setuptools]
packages = [
    "supermi",
    "supermi.api",
]

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 2

